FROM adoptopenjdk/openjdk13-openj9:latest
MAINTAINER openslice.io
RUN mkdir /opt/shareclasses
RUN mkdir -p /opt/openslice/lib/
COPY target/io.openslice.bugzilla-1.1.0-SNAPSHOT.jar /opt/openslice/lib/
CMD ["java", "-Xshareclasses:cacheDir=/opt/shareclasses","-jar", "/opt/openslice/lib/io.openslice.bugzilla-1.1.0-SNAPSHOT.jar"]