
# For Spring Actuator /info endpoint
info:
    artifact: bugzilla-client-service
    name: bugzilla-client-service
    description: Spring bugzilla-client-service
    version: 1.0.0
    
    
endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true

logging:
  level:
    org.springframework.cloud.consul: DEBUG
    org.apache.camel.zipkin: INFO
    org.apache.camel.spring.cloud: INFO
    
# Camel Service Call
camel:
  cloud:
    service-call.component: undertow
  zipkin:
    endpoint: http://localhost:9411/api/v2/spans
    server-service-mappings.[*]: bugzilla-client-service
    client-service-mappings.[*]: bugzilla-client-service
    include-message-body-streams: false