
# For Spring Actuator /info endpoint
info:
    artifact: bugzilla-client-service
    name: bugzilla-client-service
    description: Spring bugzilla-client-service
    version: 1.0.0

server:
  port: 13010
    

logging:
  level:
    root: INFO
    org.springframework.cloud.consul: INFO
    org.apache.camel.zipkin: INFO
    org.apache.camel.spring.cloud: INFO
    org.apache.camel: DEBUG
    
# Camel Service Call
camel:
  cloud:
    service-call.component: undertow
  zipkin:
    endpoint: http://localhost:9411/api/v2/spans
    server-service-mappings.[*]: bugzilla-client-service
    client-service-mappings.[*]: bugzilla-client-service
    include-message-body-streams: false
    
    
spring:
  profiles: default
  application:
    name: bugzilla-client-service
  cloud:
    consul:
      enabled: true
      host: http://localhost:8500
      port: 8500
      config:
        enabled: true
        prefix: config
        defaultContext: openslice
        data-key: osdata
        profileSeparator: '::'
        format: yaml
      discovery:        
        tags: openslice-microservice
        enabled: true
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        healthCheckInterval: 120s
      
  activemq:
    brokerUrl: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 100
      
portaltitle: "openslice"
maindomain: "http://localhost:13000"
main_operations_product: "Openslice Operations"
bugzillaurl: "bugzilla.example.org:443/bugstaging/"
bugzillakey: ""

#EVENT TOPICS IN Message Bus
EVENT_SERVICE_CREATE: "jms:topic:EVENT.SERVICE.CREATE"
EVENT_SERVICE_STATE_CHANGED: "jms:topic:EVENT.SERVICE.STATECHANGED"
EVENT_SERVICE_DELETE: "jms:topic:EVENT.SERVICE.DELETE"
EVENT_SERVICE_ATTRIBUTE_VALUE_CHANGED: "jms:topic:EVENT.SERVICE.ATTRCHANGED"
EVENT_SERVICE_ORDER_CREATE: "jms:topic:EVENT.SERVICEORDER.CREATE"
EVENT_SERVICE_ORDER_STATE_CHANGED: "jms:topic:EVENT.SERVICEORDER.STATECHANGED"
EVENT_SERVICE_ORDER_DELETE: "jms:topic:EVENT.SERVICEORDER.DELETE"
EVENT_SERVICE_ORDER_ATTRIBUTE_VALUE_CHANGED: "jms:topic:EVENT.SERVICEORDER.ATTRCHANGED"




