
# For Spring Actuator /info endpoint
info:
    artifact: bugzilla-client-service
    name: bugzilla-client-service
    description: Spring bugzilla-client-service
    version: 1.0.0

server:
  port: 13010
    

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.apache.camel.zipkin: INFO
    org.apache.camel.spring.cloud: INFO
    org.apache.camel: INFO
    

    
spring:
  config:
    activate:
      on-profile: "default"
  application:
    name: bugzilla-client-service

      
  activemq:
    brokerUrl: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 100
    packages:
      trust-all: true
      
portaltitle: "openslice"
maindomain: "http://localhost:13000"
main_operations_product: "Openslice Operations"
bugzillaurl: "bugzilla.example.org:443/bugstaging/"
bugzillakey: ""

#EVENT TOPICS IN Message Bus
EVENT_SERVICE_CREATE: "jms:topic:EVENT.SERVICE.CREATE"
EVENT_SERVICE_STATE_CHANGED: "jms:topic:EVENT.SERVICE.STATECHANGED"
EVENT_SERVICE_DELETE: "jms:topic:EVENT.SERVICE.DELETE"
EVENT_SERVICE_ATTRIBUTE_VALUE_CHANGED: "jms:topic:EVENT.SERVICE.ATTRCHANGED"
EVENT_SERVICE_ORDER_CREATE: "jms:topic:EVENT.SERVICEORDER.CREATE"
EVENT_SERVICE_ORDER_STATE_CHANGED: "jms:topic:EVENT.SERVICEORDER.STATECHANGED"
EVENT_SERVICE_ORDER_DELETE: "jms:topic:EVENT.SERVICEORDER.DELETE"
EVENT_SERVICE_ORDER_ATTRIBUTE_VALUE_CHANGED: "jms:topic:EVENT.SERVICEORDER.ATTRCHANGED"
EVENT_INDIVIDUAL_CREATE: "jms:topic:EVENT.INDIVIDUAL.CREATE"



